version: 2

models:
  - name: stg_orders
    description: Cleaned and renamed Superstore orders table
    columns:
      - name: order_id
        description: Unique identifier for each order
        tests:
          - not_null
      - name: customer_id
        description: ID of the customer
        tests:
          - not_null
      - name: sales
        description: Sales amount of the order
      - name: profit
        description: Profit from the order

  - name: fct_sales
    description: Aggregated sales and profit by category and region
    columns:
      - name: category
        description: Product category
        tests:
          - not_null
      - name: region
        description: Sales region
        tests:
          - not_null
      - name: total_sales
        description: Total sales per category/region
      - name: total_profit
        description: Total profit per category/region
      - name: total_orders
        description: Count of unique orders
